apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gh-ghactions-quay-go-dthpecno
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gh-ghactions-quay-go-dthpecno 
  name: gh-ghactions-quay-go-dthpecno
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gh-ghactions-quay-go-dthpecno 
